### ISSUE TITLE
Clean up node labels (Same case, remove zz, etc.)

### ISSUE THREAD

**Issue by bherr2** [cns-iu/hsd#19]

**Comment by axdanbol** [comment]
How should casing be done?
Explain for:
- PCORI
- ICD-11-CM
- CPT-4 and HCPCS (i.e., HCPCS Levels I and II)
- BIRTH_DATE

**Comment by bherr2** [comment]
Good question, I am awaiting feedback from the client to be sure. Only do the obvious bits for now.
