### ISSUE TITLE
Create a Tree Visualization

### ISSUE THREAD

**Issue by bherr2** [cns-iu/hsd#4]
Create a Tree visualization using provided data. Get as far as you can using a vega .json file and a linked gist (please add to comments). After that, we will move on to integration as an angular component (a separate issue).

**Comment by axdanbol** [comment]
Gist at [https://gist.github.com/axdanbol/d77ffabcc9cfb2f3c9b7d7e2404a7f8f](https://gist.github.com/axdanbol/d77ffabcc9cfb2f3c9b7d7e2404a7f8f)

**Comment by bherr2** [comment]
CSV processing + basic tree visualization with a vega.json is finished. You can view the processed data in a tree here: https://vega.github.io/editor/#/gist/vega/axdanbol/d77ffabcc9cfb2f3c9b7d7e2404a7f8f

This will eventually be integrated into the repository when we start creating components.

**Comment by katyb** [comment]
This is GREAT to see.
Also share with Griffin?
I always wanted to see this and I finally can!
k


--
Katy Borner
Victor H. Yngve Distinguished Professor of Engineering and Information Science
Director, CI for Network Science Center, http://cns.iu.edu
Curator, Mapping Science exhibit, http://scimaps.org

ISE and ILS, School of Informatics and Computing, Indiana University
Luddy Hall 4018, 700 N. Woodlawn Ave, Bloomington, IN 47408, USA
Phone: (812) 855-3256  Fax: -6166

**Comment by bherr2** [comment]
Sure! Its a work in progress, but good progress.


Thanks,

Bruce


--
Bruce W. Herr II
Senior Software Architect / Project Manager
CI for Network Science Center, http://cns.iu.edu

________________________________
