### ISSUE TITLE
Sum Box sizes do not go back to normal on expanding and then collapsing

### ISSUE THREAD

**Issue by GagsdName** [cns-iu/hsd#46]
Reproducible on https://cns-iu.github.io/hsd/ on Sum-Tree-v3. 
Note- This is not an issue on Sum-Tree-v2.

**Comment by GagsdName** [comment]
Fixed by an Evil Hack for now in sum-tree-rewrite.component.ts

**Comment by bherr2** [comment]
Evil Hack is not in the repo (that I see). Commit it when you get a chance.

**Comment by GagsdName** [comment]
Done - [1a8ea9c](https://github.com/cns-iu/hsd/commit/1a8ea9c90bbcee1f6a37ad638f48ff81ac9f1333)
