### ISSUE TITLE
Integrate sample CSV data

### ISSUE THREAD

**Issue by bherr2** [cns-iu/hsd#5]
Integrate CSV provided by Griffin for data. Get as far as you can using a vega .json file and a linked gist (please add to comments). After that, we will move on to integration into the angular repo (a separate issue).

**Comment by axdanbol** [comment]
Gist at [https://gist.github.com/axdanbol/d77ffabcc9cfb2f3c9b7d7e2404a7f8f](https://gist.github.com/axdanbol/d77ffabcc9cfb2f3c9b7d7e2404a7f8f)

**Comment by bherr2** [comment]
CSV processing with a vega.json is finished. You can view the processed data in a tree here: https://vega.github.io/editor/#/gist/vega/axdanbol/d77ffabcc9cfb2f3c9b7d7e2404a7f8f

This will eventually be integrated into the repository when we start creating components.
