### ISSUE TITLE
Change Status ordering

### ISSUE THREAD

**Issue by bherr2** [cns-iu/hsd#50]
Switch "Inactive" and "Hidden". The hierarchy is Active->Hidden->Inactive. Currently, the order of Hidden and Inactive are reversed.

**Comment by bherr2** [comment]
@axdanbol color-coding legend needs to be flipped too.

**Comment by axdanbol** [comment]
I did. Hidden was yellow before and inactive was green.

**Comment by axdanbol** [comment]
Saw that opacity need to be fixed though

**Comment by bherr2** [comment]
Ahh yes, opacity is the one needing flipped. Thanks.

**Comment by axdanbol** [comment]
Fixed now!
